name: Comment on Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  commenting_job:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Initial Comment
    steps:
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `#### Awesome! We love getting pull requests 🖌\`
            
            <details>            
            Thank you for talking the time to submit a pull request to our open source Project.
            We have notified our developers to review the changes from your PR, so you will hear from us soon.
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
